### ISSUE TITLE
Add File Asset Support

### ISSUE THREAD

**Issue by wsobel** [mtconnect/cppagent_dev#78]
Add the new File asset parsing and generation per: 

[Issue #2247](https://projects.mtconnect.org/issues/2247)

- [ ] Create Internal Representation of File Asset
- [ ] Parse File Asset XML
- [ ] Generate File Asset XML
- [ ] Generate File Asset JSON
